<a href="https://colab.research.google.com/github/saurabhrs2k/simple-codes/blob/master/house_prices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
dataset = pd.read_csv("train.csv")
df = dataset.copy()
#pd.set_option('display.max_columns',None)
df

        Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0        1          60       RL  ...        WD         Normal    208500
1        2          20       RL  ...        WD         Normal    181500
2        3          60       RL  ...        WD         Normal    223500
3        4          70       RL  ...        WD        Abnorml    140000
4        5          60       RL  ...        WD         Normal    250000
...    ...         ...      ...  ...       ...            ...       ...
1455  1456          60       RL  ...        WD         Normal    175000
1456  1457          20       RL  ...        WD         Normal    210000
1457  1458          70       RL  ...        WD         Normal    266500
1458  1459          20       RL  ...        WD         Normal    142125
1459  1460          20       RL  ...        WD         Normal    147500

[1460 rows x 81 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [ ]:
print(df.isnull().sum().to_string())

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          8
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0

In [ ]:
temp = df[["MSZoning","ExterCond","BsmtCond","KitchenQual","GarageCond","SaleCondition"]]
temp

     MSZoning ExterCond BsmtCond KitchenQual GarageCond SaleCondition
0          RL        TA       TA          Gd         TA        Normal
1          RL        TA       TA          TA         TA        Normal
2          RL        TA       TA          Gd         TA        Normal
3          RL        TA       Gd          Gd         TA       Abnorml
4          RL        TA       TA          Gd         TA        Normal
...       ...       ...      ...         ...        ...           ...
1455       RL        TA       TA          TA         TA        Normal
1456       RL        TA       TA          TA         TA        Normal
1457       RL        Gd       Gd          Gd         TA        Normal
1458       RL        TA       TA          Gd         TA        Normal
1459       RL        TA       TA          TA         TA        Normal

[1460 rows x 6 columns]

In [ ]:
temp1 = pd.get_dummies(data=temp, columns=["MSZoning","ExterCond","KitchenQual","SaleCondition","BsmtCond","GarageCond"])
temp1

      MSZoning_C (all)  MSZoning_FV  ...  GarageCond_Po  GarageCond_TA
0                    0            0  ...              0              1
1                    0            0  ...              0              1
2                    0            0  ...              0              1
3                    0            0  ...              0              1
4                    0            0  ...              0              1
...                ...          ...  ...            ...            ...
1455                 0            0  ...              0              1
1456                 0            0  ...              0              1
1457                 0            0  ...              0              1
1458                 0            0  ...              0              1
1459                 0            0  ...              0              1

[1460 rows x 29 columns]

In [ ]:
temp1.isnull().sum()

MSZoning_C (all)         0
MSZoning_FV              0
MSZoning_RH              0
MSZoning_RL              0
MSZoning_RM              0
ExterCond_Ex             0
ExterCond_Fa             0
ExterCond_Gd             0
ExterCond_Po             0
ExterCond_TA             0
KitchenQual_Ex           0
KitchenQual_Fa           0
KitchenQual_Gd           0
KitchenQual_TA           0
SaleCondition_Abnorml    0
SaleCondition_AdjLand    0
SaleCondition_Alloca     0
SaleCondition_Family     0
SaleCondition_Normal     0
SaleCondition_Partial    0
BsmtCond_Fa              0
BsmtCond_Gd              0
BsmtCond_Po              0
BsmtCond_TA              0
GarageCond_Ex            0
GarageCond_Fa            0
GarageCond_Gd            0
GarageCond_Po            0
GarageCond_TA            0
dtype: int64

In [ ]:
df = df.select_dtypes(include=["int64","float64"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   OverallQual    1460 non-null   int64
 5   OverallCond    1460 non-null   int64
 6   YearBuilt      1460 non-null   int64
 7   YearRemodAdd   1460 non-null   int64
 8   MasVnrArea     1452 non-null   float64
 9   BsmtFinSF1     1460 non-null   int64
 10  BsmtFinSF2     1460 non-null   int64
 11  BsmtUnfSF      1460 non-null   int64
 12  TotalBsmtSF    1460 non-null   int64
 13  1stFlrSF       1460 non-null   int64
 14  2ndFlrSF       1460 non-null   int64
 15  LowQualFinSF   1460 non-null   int64
 16  GrLivArea      1460 non-null   int64
 17  BsmtFullBath   1460 non-null   int64
 18  BsmtHalfBath   1460 non-null   int64
 19  FullBath       1460 non-null   int64
 20  HalfBath       1460 non-null   int64
 21  BedroomAbvGr   1460 non-null   int64
 22  KitchenAbvGr   1460 non-null   int64
 23  TotRmsAbvGrd   1460 non-null   int64
 24  Fireplaces     1460 non-null   int64
 25  GarageYrBlt    1379 non-null   float64
 26  GarageCars     1460 non-null   int64
 27  GarageArea     1460 non-null   int64
 28  WoodDeckSF     1460 non-null   int64
 29  OpenPorchSF    1460 non-null   int64
 30  EnclosedPorch  1460 non-null   int64
 31  3SsnPorch      1460 non-null   int64
 32  ScreenPorch    1460 non-null   int64
 33  PoolArea       1460 non-null   int64
 34  MiscVal        1460 non-null   int64
 35  MoSold         1460 non-null   int64
 36  YrSold         1460 non-null   int64
 37  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35)
memory usage: 433.6 KB

In [ ]:
df.isnull().sum()

Id                 0
MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [ ]:
df["LotFrontage"]=df["LotFrontage"].fillna(value=0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df.isnull().sum()

Id                0
MSSubClass        0
LotFrontage       0
LotArea           0
OverallQual       0
OverallCond       0
YearBuilt         0
YearRemodAdd      0
MasVnrArea        8
BsmtFinSF1        0
BsmtFinSF2        0
BsmtUnfSF         0
TotalBsmtSF       0
1stFlrSF          0
2ndFlrSF          0
LowQualFinSF      0
GrLivArea         0
BsmtFullBath      0
BsmtHalfBath      0
FullBath          0
HalfBath          0
BedroomAbvGr      0
KitchenAbvGr      0
TotRmsAbvGrd      0
Fireplaces        0
GarageYrBlt      81
GarageCars        0
GarageArea        0
WoodDeckSF        0
OpenPorchSF       0
EnclosedPorch     0
3SsnPorch         0
ScreenPorch       0
PoolArea          0
MiscVal           0
MoSold            0
YrSold            0
SalePrice         0
dtype: int64

In [ ]:
df["MasVnrArea"]=df["MasVnrArea"].fillna(value=0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df.isnull().sum()

Id                0
MSSubClass        0
LotFrontage       0
LotArea           0
OverallQual       0
OverallCond       0
YearBuilt         0
YearRemodAdd      0
MasVnrArea        0
BsmtFinSF1        0
BsmtFinSF2        0
BsmtUnfSF         0
TotalBsmtSF       0
1stFlrSF          0
2ndFlrSF          0
LowQualFinSF      0
GrLivArea         0
BsmtFullBath      0
BsmtHalfBath      0
FullBath          0
HalfBath          0
BedroomAbvGr      0
KitchenAbvGr      0
TotRmsAbvGrd      0
Fireplaces        0
GarageYrBlt      81
GarageCars        0
GarageArea        0
WoodDeckSF        0
OpenPorchSF       0
EnclosedPorch     0
3SsnPorch         0
ScreenPorch       0
PoolArea          0
MiscVal           0
MoSold            0
YrSold            0
SalePrice         0
dtype: int64

In [ ]:
df.drop("GarageYrBlt",axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
df.isnull().sum()

Id               0
MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
dtype: int64

In [ ]:
df

        Id  MSSubClass  LotFrontage  ...  MoSold  YrSold  SalePrice
0        1          60         65.0  ...       2    2008     208500
1        2          20         80.0  ...       5    2007     181500
2        3          60         68.0  ...       9    2008     223500
3        4          70         60.0  ...       2    2006     140000
4        5          60         84.0  ...      12    2008     250000
...    ...         ...          ...  ...     ...     ...        ...
1455  1456          60         62.0  ...       8    2007     175000
1456  1457          20         85.0  ...       2    2010     210000
1457  1458          70         66.0  ...       5    2010     266500
1458  1459          20         68.0  ...       4    2010     142125
1459  1460          20         75.0  ...       6    2008     147500

[1460 rows x 37 columns]

In [ ]:
df = pd.concat([df,temp1],axis=1)
df

        Id  MSSubClass  ...  GarageCond_Po  GarageCond_TA
0        1          60  ...              0              1
1        2          20  ...              0              1
2        3          60  ...              0              1
3        4          70  ...              0              1
4        5          60  ...              0              1
...    ...         ...  ...            ...            ...
1455  1456          60  ...              0              1
1456  1457          20  ...              0              1
1457  1458          70  ...              0              1
1458  1459          20  ...              0              1
1459  1460          20  ...              0              1

[1460 rows x 66 columns]

In [ ]:
print(df.isnull().sum().to_string())

Id                       0
MSSubClass               0
LotFrontage              0
LotArea                  0
OverallQual              0
OverallCond              0
YearBuilt                0
YearRemodAdd             0
MasVnrArea               0
BsmtFinSF1               0
BsmtFinSF2               0
BsmtUnfSF                0
TotalBsmtSF              0
1stFlrSF                 0
2ndFlrSF                 0
LowQualFinSF             0
GrLivArea                0
BsmtFullBath             0
BsmtHalfBath             0
FullBath                 0
HalfBath                 0
BedroomAbvGr             0
KitchenAbvGr             0
TotRmsAbvGrd             0
Fireplaces               0
GarageCars               0
GarageArea               0
WoodDeckSF               0
OpenPorchSF              0
EnclosedPorch            0
3SsnPorch                0
ScreenPorch              0
PoolArea                 0
MiscVal                  0
MoSold                   0
YrSold                   0
SalePrice                0
MSZoning_C (all)         0
MSZoning_FV              0
MSZoning_RH              0
MSZoning_RL              0
MSZoning_RM              0
ExterCond_Ex             0
ExterCond_Fa             0
ExterCond_Gd             0
ExterCond_Po             0
ExterCond_TA             0
KitchenQual_Ex           0
KitchenQual_Fa           0
KitchenQual_Gd           0
KitchenQual_TA           0
SaleCondition_Abnorml    0
SaleCondition_AdjLand    0
SaleCondition_Alloca     0
SaleCondition_Family     0
SaleCondition_Normal     0
SaleCondition_Partial    0
BsmtCond_Fa              0
BsmtCond_Gd              0
BsmtCond_Po              0
BsmtCond_TA              0
GarageCond_Ex            0
GarageCond_Fa            0
GarageCond_Gd            0
GarageCond_Po            0
GarageCond_TA            0

In [ ]:
y = df["SalePrice"]
feature = df.drop("SalePrice",axis = 1)
X = feature
X.set_index("Id",drop=True)

      MSSubClass  LotFrontage  ...  GarageCond_Po  GarageCond_TA
Id                             ...
1             60         65.0  ...              0              1
2             20         80.0  ...              0              1
3             60         68.0  ...              0              1
4             70         60.0  ...              0              1
5             60         84.0  ...              0              1
...          ...          ...  ...            ...            ...
1456          60         62.0  ...              0              1
1457          20         85.0  ...              0              1
1458          70         66.0  ...              0              1
1459          20         68.0  ...              0              1
1460          20         75.0  ...              0              1

[1460 rows x 64 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size = 0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
reg = GradientBoostingRegressor(random_state=0)
reg.fit(X_train, Y_train)

GradientBoostingRegressor(random_state=0)

In [ ]:
acc = reg.score(X_test, Y_test)
acc

0.8814156617154386

In [ ]:
test = pd.read_csv("test.csv")
df_test = test.copy()
df_test

        Id  MSSubClass MSZoning  ...  YrSold  SaleType SaleCondition
0     1461          20       RH  ...    2010        WD        Normal
1     1462          20       RL  ...    2010        WD        Normal
2     1463          60       RL  ...    2010        WD        Normal
3     1464          60       RL  ...    2010        WD        Normal
4     1465         120       RL  ...    2010        WD        Normal
...    ...         ...      ...  ...     ...       ...           ...
1454  2915         160       RM  ...    2006        WD        Normal
1455  2916         160       RM  ...    2006        WD       Abnorml
1456  2917          20       RL  ...    2006        WD       Abnorml
1457  2918          85       RL  ...    2006        WD        Normal
1458  2919          60       RL  ...    2006        WD        Normal

[1459 rows x 80 columns]

In [ ]:
temp2 = df_test[["MSZoning","ExterCond","BsmtCond","KitchenQual","GarageCond","SaleCondition"]]
temp2

     MSZoning ExterCond BsmtCond KitchenQual GarageCond SaleCondition
0          RH        TA       TA          TA         TA        Normal
1          RL        TA       TA          Gd         TA        Normal
2          RL        TA       TA          TA         TA        Normal
3          RL        TA       TA          Gd         TA        Normal
4          RL        TA       TA          Gd         TA        Normal
...       ...       ...      ...         ...        ...           ...
1454       RM        TA       TA          TA        NaN        Normal
1455       RM        TA       TA          TA         TA       Abnorml
1456       RL        TA       TA          TA         TA       Abnorml
1457       RL        TA       TA          TA        NaN        Normal
1458       RL        TA       TA          TA         TA        Normal

[1459 rows x 6 columns]

In [ ]:
temp3 = pd.get_dummies(data=temp2, columns=["MSZoning","ExterCond","KitchenQual","SaleCondition","BsmtCond","GarageCond"])
temp3

      MSZoning_C (all)  MSZoning_FV  ...  GarageCond_Po  GarageCond_TA
0                    0            0  ...              0              1
1                    0            0  ...              0              1
2                    0            0  ...              0              1
3                    0            0  ...              0              1
4                    0            0  ...              0              1
...                ...          ...  ...            ...            ...
1454                 0            0  ...              0              0
1455                 0            0  ...              0              1
1456                 0            0  ...              0              1
1457                 0            0  ...              0              0
1458                 0            0  ...              0              1

[1459 rows x 29 columns]

In [ ]:
print(temp3.isnull().sum().to_string())

MSZoning_C (all)         0
MSZoning_FV              0
MSZoning_RH              0
MSZoning_RL              0
MSZoning_RM              0
ExterCond_Ex             0
ExterCond_Fa             0
ExterCond_Gd             0
ExterCond_Po             0
ExterCond_TA             0
KitchenQual_Ex           0
KitchenQual_Fa           0
KitchenQual_Gd           0
KitchenQual_TA           0
SaleCondition_Abnorml    0
SaleCondition_AdjLand    0
SaleCondition_Alloca     0
SaleCondition_Family     0
SaleCondition_Normal     0
SaleCondition_Partial    0
BsmtCond_Fa              0
BsmtCond_Gd              0
BsmtCond_Po              0
BsmtCond_TA              0
GarageCond_Ex            0
GarageCond_Fa            0
GarageCond_Gd            0
GarageCond_Po            0
GarageCond_TA            0

In [ ]:
df_test = df_test.select_dtypes(include=["int64","float64"])
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 37 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   LotFrontage    1232 non-null   float64
 3   LotArea        1459 non-null   int64
 4   OverallQual    1459 non-null   int64
 5   OverallCond    1459 non-null   int64
 6   YearBuilt      1459 non-null   int64
 7   YearRemodAdd   1459 non-null   int64
 8   MasVnrArea     1444 non-null   float64
 9   BsmtFinSF1     1458 non-null   float64
 10  BsmtFinSF2     1458 non-null   float64
 11  BsmtUnfSF      1458 non-null   float64
 12  TotalBsmtSF    1458 non-null   float64
 13  1stFlrSF       1459 non-null   int64
 14  2ndFlrSF       1459 non-null   int64
 15  LowQualFinSF   1459 non-null   int64
 16  GrLivArea      1459 non-null   int64
 17  BsmtFullBath   1457 non-null   float64
 18  BsmtHalfBath   1457 non-null   float64
 19  FullBath       1459 non-null   int64
 20  HalfBath       1459 non-null   int64
 21  BedroomAbvGr   1459 non-null   int64
 22  KitchenAbvGr   1459 non-null   int64
 23  TotRmsAbvGrd   1459 non-null   int64
 24  Fireplaces     1459 non-null   int64
 25  GarageYrBlt    1381 non-null   float64
 26  GarageCars     1458 non-null   float64
 27  GarageArea     1458 non-null   float64
 28  WoodDeckSF     1459 non-null   int64
 29  OpenPorchSF    1459 non-null   int64
 30  EnclosedPorch  1459 non-null   int64
 31  3SsnPorch      1459 non-null   int64
 32  ScreenPorch    1459 non-null   int64
 33  PoolArea       1459 non-null   int64
 34  MiscVal        1459 non-null   int64
 35  MoSold         1459 non-null   int64
 36  YrSold         1459 non-null   int64
dtypes: float64(11), int64(26)
memory usage: 421.9 KB

In [ ]:
df_test.isnull().sum()

Id                 0
MSSubClass         0
LotFrontage      227
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea        15
BsmtFinSF1         1
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       2
BsmtHalfBath       2
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       78
GarageCars         1
GarageArea         1
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
dtype: int64

In [ ]:
df_test["LotFrontage"]=df_test["LotFrontage"].fillna(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_test.isnull().sum()

Id                0
MSSubClass        0
LotFrontage       0
LotArea           0
OverallQual       0
OverallCond       0
YearBuilt         0
YearRemodAdd      0
MasVnrArea       15
BsmtFinSF1        1
BsmtFinSF2        1
BsmtUnfSF         1
TotalBsmtSF       1
1stFlrSF          0
2ndFlrSF          0
LowQualFinSF      0
GrLivArea         0
BsmtFullBath      2
BsmtHalfBath      2
FullBath          0
HalfBath          0
BedroomAbvGr      0
KitchenAbvGr      0
TotRmsAbvGrd      0
Fireplaces        0
GarageYrBlt      78
GarageCars        1
GarageArea        1
WoodDeckSF        0
OpenPorchSF       0
EnclosedPorch     0
3SsnPorch         0
ScreenPorch       0
PoolArea          0
MiscVal           0
MoSold            0
YrSold            0
dtype: int64

In [ ]:
df_test["MasVnrArea"]=df_test["MasVnrArea"].fillna(value=0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_test.isnull().sum()

Id                0
MSSubClass        0
LotFrontage       0
LotArea           0
OverallQual       0
OverallCond       0
YearBuilt         0
YearRemodAdd      0
MasVnrArea        0
BsmtFinSF1        1
BsmtFinSF2        1
BsmtUnfSF         1
TotalBsmtSF       1
1stFlrSF          0
2ndFlrSF          0
LowQualFinSF      0
GrLivArea         0
BsmtFullBath      2
BsmtHalfBath      2
FullBath          0
HalfBath          0
BedroomAbvGr      0
KitchenAbvGr      0
TotRmsAbvGrd      0
Fireplaces        0
GarageYrBlt      78
GarageCars        1
GarageArea        1
WoodDeckSF        0
OpenPorchSF       0
EnclosedPorch     0
3SsnPorch         0
ScreenPorch       0
PoolArea          0
MiscVal           0
MoSold            0
YrSold            0
dtype: int64

In [ ]:
df_test.drop("GarageYrBlt",axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
df_test.isnull().sum()

Id               0
MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       1
BsmtFinSF2       1
BsmtUnfSF        1
TotalBsmtSF      1
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     2
BsmtHalfBath     2
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageCars       1
GarageArea       1
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
dtype: int64

In [ ]:
df_test.fillna(0,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,

In [ ]:
df_test.isnull().sum()

Id               0
MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
dtype: int64

In [ ]:
'''df_test.loc[df_test["YearBuilt"] > 1999, "YearBuilt"] = 1
df_test.loc[df_test["YearBuilt"] > 1000, "YearBuilt"] = 0'''

'df_test.loc[df_test["YearBuilt"] > 1999, "YearBuilt"] = 1\ndf_test.loc[df_test["YearBuilt"] > 1000, "YearBuilt"] = 0'

In [ ]:
df_test = pd.concat([df_test,temp3],axis=1)
df_test

        Id  MSSubClass  ...  GarageCond_Po  GarageCond_TA
0     1461          20  ...              0              1
1     1462          20  ...              0              1
2     1463          60  ...              0              1
3     1464          60  ...              0              1
4     1465         120  ...              0              1
...    ...         ...  ...            ...            ...
1454  2915         160  ...              0              0
1455  2916         160  ...              0              1
1456  2917          20  ...              0              1
1457  2918          85  ...              0              0
1458  2919          60  ...              0              1

[1459 rows x 65 columns]

In [ ]:
print(df_test.isnull().sum().to_string())

Id                       0
MSSubClass               0
LotFrontage              0
LotArea                  0
OverallQual              0
OverallCond              0
YearBuilt                0
YearRemodAdd             0
MasVnrArea               0
BsmtFinSF1               0
BsmtFinSF2               0
BsmtUnfSF                0
TotalBsmtSF              0
1stFlrSF                 0
2ndFlrSF                 0
LowQualFinSF             0
GrLivArea                0
BsmtFullBath             0
BsmtHalfBath             0
FullBath                 0
HalfBath                 0
BedroomAbvGr             0
KitchenAbvGr             0
TotRmsAbvGrd             0
Fireplaces               0
GarageCars               0
GarageArea               0
WoodDeckSF               0
OpenPorchSF              0
EnclosedPorch            0
3SsnPorch                0
ScreenPorch              0
PoolArea                 0
MiscVal                  0
MoSold                   0
YrSold                   0
MSZoning_C (all)         0
MSZoning_FV              0
MSZoning_RH              0
MSZoning_RL              0
MSZoning_RM              0
ExterCond_Ex             0
ExterCond_Fa             0
ExterCond_Gd             0
ExterCond_Po             0
ExterCond_TA             0
KitchenQual_Ex           0
KitchenQual_Fa           0
KitchenQual_Gd           0
KitchenQual_TA           0
SaleCondition_Abnorml    0
SaleCondition_AdjLand    0
SaleCondition_Alloca     0
SaleCondition_Family     0
SaleCondition_Normal     0
SaleCondition_Partial    0
BsmtCond_Fa              0
BsmtCond_Gd              0
BsmtCond_Po              0
BsmtCond_TA              0
GarageCond_Ex            0
GarageCond_Fa            0
GarageCond_Gd            0
GarageCond_Po            0
GarageCond_TA            0

In [ ]:
df_test.set_index("Id",drop=True)

      MSSubClass  LotFrontage  ...  GarageCond_Po  GarageCond_TA
Id                             ...
1461          20         80.0  ...              0              1
1462          20         81.0  ...              0              1
1463          60         74.0  ...              0              1
1464          60         78.0  ...              0              1
1465         120         43.0  ...              0              1
...          ...          ...  ...            ...            ...
2915         160         21.0  ...              0              0
2916         160         21.0  ...              0              1
2917          20        160.0  ...              0              1
2918          85         62.0  ...              0              0
2919          60         74.0  ...              0              1

[1459 rows x 64 columns]

In [ ]:
Xfinal = df_test
Xfinal.set_index("Id",drop=True)

      MSSubClass  LotFrontage  ...  GarageCond_Po  GarageCond_TA
Id                             ...
1461          20         80.0  ...              0              1
1462          20         81.0  ...              0              1
1463          60         74.0  ...              0              1
1464          60         78.0  ...              0              1
1465         120         43.0  ...              0              1
...          ...          ...  ...            ...            ...
2915         160         21.0  ...              0              0
2916         160         21.0  ...              0              1
2917          20        160.0  ...              0              1
2918          85         62.0  ...              0              0
2919          60         74.0  ...              0              1

[1459 rows x 64 columns]

In [ ]:
Xfinal = sc.fit_transform(Xfinal)

In [ ]:
pred = reg.predict(Xfinal)
pred

array([124704.35197682, 162777.73766075, 187023.03600965, ...,
       178533.70059141, 126267.12194987, 241921.90544877])

In [ ]:
final = df_test["Id"]
fpred= pd.DataFrame(pred)
final = pd.concat([final,fpred],axis=1)
final.set_index("Id",inplace=True)


final

                  0
Id
1461  124704.351977
1462  162777.737661
1463  187023.036010
1464  190946.050580
1465  205045.947428
...             ...
2915   78581.256338
2916   82955.459217
2917  178533.700591
2918  126267.121950
2919  241921.905449

[1459 rows x 1 columns]

In [ ]:
final.rename(columns={0:"SalePrice"},inplace= True)
final

          SalePrice
Id
1461  124704.351977
1462  162777.737661
1463  187023.036010
1464  190946.050580
1465  205045.947428
...             ...
2915   78581.256338
2916   82955.459217
2917  178533.700591
2918  126267.121950
2919  241921.905449

[1459 rows x 1 columns]

In [ ]:
final.to_csv("SalePrice.csv")